import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import { mercadoLivreReadHeaders } from "../lib/cloudinary-stage2-pilot.mjs";
test("piloto real tem allowlist exata, limite três e não escreve banco/marketplace",()=>{const s=fs.readFileSync(new URL("../scripts/cloudinary-stage2-pilot.mjs",import.meta.url),"utf8");for(const id of ["produtos/LG/1239KTKT_32LN5400_02","produtos/LG/815PFPF_65NANO81SNA_EAX68248021_02_2dedb9ca58","produtos/LG/816PFDPF_55QNED80SRA_EAY65895417_04_8801e764b0"])assert.match(s,new RegExp(id));assert.match(s,/--execute-stage2b-exact-3/);assert.doesNotMatch(s,/\.from\([^)]*\)\.(insert|update|delete|upsert)/);assert.doesNotMatch(s,/resources\/backup\/.*DELETE/)});
test("preflight-only termina antes de backups e escritas externas",()=>{const s=fs.readFileSync(new URL("../scripts/cloudinary-stage2-pilot.mjs",import.meta.url),"utf8"),guard=s.search(/if\s*\(mode\s*===\s*"preflight"\)/),backup=s.indexOf("fs.mkdirSync(BACKUPS"),loop=s.search(/for\s*\(const p of prepared\)/);assert.ok(guard>0);assert.ok(guard<backup);assert.ok(guard<loop);assert.match(s,/PASS: preflight concluído sem qualquer escrita/)});
test("erros externos expõem somente diagnóstico seguro",()=>{const s=fs.readFileSync(new URL("../scripts/cloudinary-stage2-pilot.mjs",import.meta.url),"utf8");for(const field of ["source","operation","http_status","method","hostname","safe_message"])assert.match(s,new RegExp(field));assert.match(s,/split\("\?"\)\[0\]/);assert.match(s,/\[REDACTED\]/)});
test("Mercado Livre usa Bearer somente da conta correspondente",()=>{const link={marketplace_account_id:"account-2"},accounts=[{id:"account-1",marketplace:"mercado_livre",access_token:"wrong"},{id:"account-2",marketplace:"mercado_livre",access_token:"correct"},{id:"account-2",marketplace:"shopee",access_token:"also-wrong"}];assert.deepEqual(mercadoLivreReadHeaders(link,accounts),{Authorization:"Bearer correct"})});
test("Mercado Livre bloqueia conta ausente sem expor token",()=>{assert.throws(()=>mercadoLivreReadHeaders({marketplace_account_id:"missing"},[{id:"other",marketplace:"mercado_livre",access_token:"super-secret"}]),error=>error.message==="conta Mercado Livre não encontrada"&&!error.message.includes("super-secret"))});
test("Mercado Livre bloqueia token expirado e proíbe refresh",()=>{assert.throws(()=>mercadoLivreReadHeaders({marketplace_account_id:"a"},[{id:"a",marketplace:"mercado_livre",access_token:"super-secret",token_expires_at:"2025-01-01T00:00:00Z"}],Date.parse("2026-01-01T00:00:00Z")),error=>error.message==="token Mercado Livre expirado; refresh proibido"&&!error.message.includes("super-secret"));const source=fs.readFileSync(new URL("../scripts/cloudinary-stage2-pilot.mjs",import.meta.url),"utf8");assert.doesNotMatch(source,/refresh[_-]?token|oauth\/token/i)});
test("preflight Mercado Livre permanece somente leitura",()=>{const source=fs.readFileSync(new URL("../scripts/cloudinary-stage2-pilot.mjs",import.meta.url),"utf8");assert.match(source,/source:\s*"mercado-livre",\s*operation:\s*"item-details"/);assert.match(source,/api\.mercadolibre\.com\/items/);assert.doesNotMatch(source,/api\.mercadolibre\.com[^\n]*(POST|PUT|PATCH|DELETE)/)});
